name: voicebot_proj

services:
  voicebot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: voicebot
    restart: unless-stopped
    env_file:
      - ../.env
    volumes:
      - ../voicebot.db:/app/voicebot.db
    networks:
      - voicenet

networks:
  voicenet: