name: voicebot_proj

services:
  voicebot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: voicebot
    restart: unless-stopped
    env_file:
      - ../.env
    volumes:
      - /root/projects/sharing/tg-voicebot:/root/projects/sharing/tg-voicebot
      - /root/projects/bots/voicebot/voice_stats.db:/app/voice_stats.db
    networks:
      - voicenet

networks:
  voicenet: